#!/usr/bin/env bash


cd ~/.dotfiles/shell &> /dev/null || return 0
profile_hook_exit_code=0
source init.sh "bash" "env" || profile_hook_exit_code=$?
if [ ! $profile_hook_exit_code -eq 0 ]; then
    cd ~ &> /dev/null
    echo "[bash|env] Profile hook failed, returned code '$profile_hook_exit_code'. (bash_profile)" >&2
    unset profile_hook_exit_code
    return 0
fi

source init.sh "bash" "login" || profile_hook_exit_code=$?
if [ ! $profile_hook_exit_code -eq 0 ]; then
    cd ~ &> /dev/null
    echo "[bash|login] Profile hook failed, returned code '$profile_hook_exit_code'. (bash_profile)" >&2
    unset profile_hook_exit_code
    return 0
fi

source init.sh "bash" "rc" || profile_hook_exit_code=$?
cd ~ &> /dev/null
if [ ! $profile_hook_exit_code -eq 0 ]; then
    echo "[bash|rc] Profile hook failed, returned code '$profile_hook_exit_code'. (bash_profile)" >&2
    unset profile_hook_exit_code
    return 0
fi
