#!/usr/bin/env bash


cd ~/.dotfiles/shell &> /dev/null || return 0

if [ -z "$PROFILE_STAGE" ] || [[ ! "$PROFILE_STAGE" =~ ^bash.* ]]; then
    export PROFILE_STAGE
    PROFILE_STAGE="bash➡️env"; profile_hook_exit_code=0
    source ./init.sh "bash" "env" || profile_hook_exit_code=$?
    if [ "$profile_hook_exit_code" -ne 0 ]; then
        cd ~ &> /dev/null
        echo "[bash|env] Profile hook failed, returned code '$profile_hook_exit_code'. (bashrc)" >&2
        unset profile_hook_exit_code
        PROFILE_STAGE="bash@env❌"
        return 0
    else
        PROFILE_STAGE="bash@env✅"
    fi
fi

if [ "$PROFILE_STAGE" = "bash@env✅" ]; then
    PROFILE_STAGE="bash@➡️login"; profile_hook_exit_code=0
    source ./init.sh "bash" "login" || profile_hook_exit_code=$?
    if [ "$profile_hook_exit_code" -ne 0 ]; then
        cd ~ &> /dev/null
        echo "[bash|login] Profile hook failed, returned code '$profile_hook_exit_code'. (bashrc)" >&2
        unset profile_hook_exit_code
        PROFILE_STAGE="bash@login❌"
        return 0
    else
        PROFILE_STAGE="bash@login✅"
    fi
fi

if [ "$PROFILE_STAGE" = "bash@login✅" ]; then
    PROFILE_STAGE="bash@➡️rc"; profile_hook_exit_code=0
    source ./init.sh "bash" "rc" || profile_hook_exit_code=$?
    cd ~ &> /dev/null
    if [ ! $profile_hook_exit_code -eq 0 ]; then
        echo "[bash|rc] Profile hook failed, returned code '$profile_hook_exit_code'.  (bashrc)" >&2
        unset profile_hook_exit_code
        PROFILE_STAGE="bash@rc❌"
        return 0
    else
        PROFILE_STAGE="bash@rc✅"
    fi
fi

cd ~ &> /dev/null
