#!/usr/bin/env bash


DOTFILES="${DOTFILES:-$HOME/.dotfiles}"; export DOTFILES;
_OLD_PWD="$PWD"
cd "$DOTFILES/shell" &> /dev/null || return 0

profile_hook_exit_code=0
PROFILE_STAGE="bash➡️logout"; export PROFILE_STAGE
source ./init.sh "bash" "logout" || profile_hook_exit_code=$?
if [ ! $profile_hook_exit_code -eq 0 ]; then
    cd "$_OLD_PWD" &> /dev/null
    unset OLD_PWD
    echo "[bash|logout] Profile hook failed, returned code '$profile_hook_exit_code'. (bash_logout)" >&2
    unset profile_hook_exit_code
    PROFILE_STAGE="bash@logout❌"
    return 0
else
    PROFILE_STAGE="bash@logout✅"
fi

cd "$_OLD_PWD" &> /dev/null
unset OLD_PWD
