#!/usr/bin/env bash


DOTFILES="${DOTFILES:-$HOME/.dotfiles}"; export DOTFILES;
_OLD_PWD="$PWD"
cd "$DOTFILES/shell" &> /dev/null || return 0

profile_hook_exit_code=0
source ./init.sh "ssh" "rc" || profile_hook_exit_code=$?
if [ ! $profile_hook_exit_code -eq 0 ]; then
    cd "$_OLD_PWD" &> /dev/null
    unset OLD_PWD
    echo "[ssh|rc] Profile hook failed, returned code '$profile_hook_exit_code'.  (sshrc)" >&2
    unset profile_hook_exit_code
    return 0
fi

cd "$_OLD_PWD" &> /dev/null
unset OLD_PWD
