#!/usr/bin/env zsh


cd ~/.dotfiles/shell &> /dev/null || return 0
local profile_hook_exit_code=0
PROFILE_STAGE="zsh➡️logout"; export PROFILE_STAGE
source init.sh "zsh" "logout" || profile_hook_exit_code=$?
cd ~ &> /dev/null
if [ ! $profile_hook_exit_code -eq 0 ]; then
    echo "[zsh|logout] Profile hook failed, returned code '$profile_hook_exit_code'. (zlogout)" >&2
    PROFILE_STAGE="zsh@logout❌"
    return 0
else
    PROFILE_STAGE="zsh@logout✅"
fi
