#!/usr/bin/env zsh


if [ -z "$PROFILE_STAGE" ] || [[ ! "$PROFILE_STAGE" =~ ^zsh.* ]]; then
    export PROFILE_STAGE
    PROFILE_STAGE="zsh➡️env"; profile_hook_exit_code=0
    source init.sh "zsh" "env" || profile_hook_exit_code=$?
    if [ "$profile_hook_exit_code" -ne 0 ]; then
        cd ~ &> /dev/null
        echo "[zsh|env] Profile hook failed, returned code '$profile_hook_exit_code'. (zprofile)" >&2
        unset profile_hook_exit_code
        PROFILE_STAGE="zsh@env❌"
        return 0
    else
        PROFILE_STAGE="zsh@env✅"
    fi
fi

if [ "$PROFILE_STAGE" = "zsh@env✅" ]; then
    PROFILE_STAGE="zsh➡️login"; profile_hook_exit_code=0
    source init.sh "zsh" "login" || profile_hook_exit_code=$?
    if [ "$profile_hook_exit_code" -ne 0 ]; then
        cd ~ &> /dev/null
        echo "[zsh|login] Profile hook failed, returned code '$profile_hook_exit_code'. (zprofile)" >&2
        unset profile_hook_exit_code
        PROFILE_STAGE="zsh@login❌"
        return 0
    else
        PROFILE_STAGE="zsh@login✅"
    fi
fi

cd ~ &> /dev/null
