#!/usr/bin/env zsh


cd ~/.dotfiles/shell &> /dev/null || return 0

if [ -z "$PROFILE_STAGE" ] || [[ ! "$PROFILE_STAGE" =~ ^zsh.* ]]; then
    export PROFILE_STAGE
    PROFILE_STAGE="zsh➡️env"; profile_hook_exit_code=0
    source init.sh "zsh" "env" || profile_hook_exit_code=$?
    if [ "$profile_hook_exit_code" -ne 0 ]; then
        cd ~ &> /dev/null
        echo "[zsh|env] Profile hook failed, returned code '$profile_hook_exit_code'. (zshrc)" >&2
        unset profile_hook_exit_code
        PROFILE_STAGE="zsh@env❌"
        return 0
    else
        PROFILE_STAGE="zsh@env✅"
    fi
fi

if [ "$PROFILE_STAGE" = "zsh@env✅" ]; then
    PROFILE_STAGE="zsh➡️login"; profile_hook_exit_code=0
    source init.sh "zsh" "login" || profile_hook_exit_code=$?
    if [ "$profile_hook_exit_code" -ne 0 ]; then
        cd ~ &> /dev/null
        echo "[zsh|login] Profile hook failed, returned code '$profile_hook_exit_code'. (zshrc)" >&2
        unset profile_hook_exit_code
        PROFILE_STAGE="zsh@login❌"
        return 0
    else
        PROFILE_STAGE="zsh@login✅"
    fi
fi

if [ "$PROFILE_STAGE" = "zsh@login✅" ]; then
    PROFILE_STAGE="zsh➡️rc"; profile_hook_exit_code=0
    source init.sh "zsh" "rc" || profile_hook_exit_code=$?
    cd ~ &> /dev/null
    if [ ! $profile_hook_exit_code -eq 0 ]; then
        echo "[zsh|rc] Profile hook failed, returned code '$profile_hook_exit_code'.  (zshrc)" >&2
        unset profile_hook_exit_code
        PROFILE_STAGE="zsh@rc❌"
        return 0
    else
        PROFILE_STAGE="zsh@rc✅"
    fi
fi

cd ~ &> /dev/null
