#!/usr/bin/env zsh


cd ~/.dotfiles/shell &> /dev/null || return 0
local profile_hook_exit_code=0
source init.sh "zsh" "rc" || profile_hook_exit_code=$?
cd ~ &> /dev/null
if [ ! $profile_hook_exit_code -eq 0 ]; then
    echo "[zsh|rc] Profile hook failed, returned code '$profile_hook_exit_code'." >&2
    return 0
fi
