###+++--- GPGConf ---+++###
no-allow-external-cache
no-allow-mark-trusted
no-allow-loopback-pinentry
grab
default-cache-ttl 1800
max-cache-ttl 1800
max-cache-ttl-ssh 1800
###+++--- GPGConf ---+++### 03/31/26 16:03:41 Mountain Daylight Time
# GPGConf edited this configuration file.
# It will disable options before this marked block, but it will
# never change anything below these lines.
enable-ssh-support
enable-win32-openssh-support
enable-putty-support
