#!/usr/bin/env bash


# Based on code from https://stackoverflow.com/a/70610357
_assert_sourced() {
    # set -e

    script="$1"
    shift 1
    varname=''
    val=''

    script="$(_concatenate_paths "$PWD" "$script")"

    varname=$(printf '__REQUIRED__%s' "${script//[^[:alnum:]]/__}")
    # loop over any arguments add to the varname
    for arg in "$@"; do
        varname=$(printf '%s__%s' "$varname" "${arg//[^[:alnum:]]/__}")
    done

    val=$(eval "printf '%s' \"\$$varname\"")
    if [ -z "$val" ]; then
        eval "$varname=1"

        unset val
        unset varname
        unset script
        return 1
    else
        unset val
        unset varname
        unset script
        return 0
    fi
}
