#!/usr/bin/env bash


function _log_info() {
    # set -e

    declare -i BMDSH_LOG_INFO_DEFAULT=0
    local -r message="$1"
    if [ "${BMDSH_LOG_INFO:-${BMDSH_LOG_INFO_DEFAULT}}" -eq 0 ]; then
        return 0
    else
        echo -e "\e[1;34m[INFO]\e[0m $message" >&2
    fi
}
