#!/usr/bin/env sh


_phook_push() {
    if [ -z "$1" ]; then
        return 2
    fi
    if [ -z "$phook_loader_q" ]; then
        phook_loader_q_length=1
    else
        phook_loader_q_length=$((phook_loader_q_length + 1))
    fi
    strlist_prepend "phook_loader_q" "${phook_loader_q_separator:?}" "$1"
    return $?
}
