#!/usr/bin/env bash


function _pip_package_location() {
    # set -e

    local grep_bin
    grep_bin="$(find_binary "grep")"
    local sed_bin
    sed_bin="$(find_binary "sed")"

    pip_show_package="$(PIP_REQUIRE_VIRTUALENV="" pip show "$1")"
    if [ -n "$pip_show_package" ]; then
        packages_location="$(echo "$pip_show_package" | $grep_bin '^Location: ' | $sed_bin 's/^Location: //')"
        printf "%s/%s" "$packages_location" "$1"
    fi
}
