#!/usr/bin/env bash


function _python3() {
    # set -e

    if [ -n "$PYTHON3" ]; then
        "$PYTHON3" "$@"
        return $?
    elif binary_exists "python3"; then
        python3 "$@"
        return $?
    else
        echo "Binary not found: 'python3'." >&2
        return 127
    fi
}
