#!/usr/bin/env bash


# Checks for existence of a command.
function command_exists() {
    # set -e

    local -r command_name="$1"
    if [ -z "$command_name" ]; then
        echo "Usage: command_exists <command_name>" >&2
        return 2
    fi

    if [ -n "$BASH_VERSION" ]; then
        if type -t "$command_name" > /dev/null; then
            return 0
        else
            return 1
        fi
    elif [ -n "$ZSH_VERSION" ]; then
        if ! command -v whence &> /dev/null; then
            echo "whence not found." >&2
            return 127
        fi
        if whence -w "$command_name" > /dev/null; then
            return 0
        else
            return 1
        fi
    else
        echo "Unknown shell: '$SHELL'." >&2
        return 2
    fi
}
