#!/usr/bin/env bash


function find_binary() {
    # set -e

    local -r binary_name="$1"
    local -r usage="Usage: find_binary <binary_name>"
    if [ -z "$binary_name" ]; then
        echo "$usage" >&2
        return 2
    fi
    if [ $# -ne 1 ]; then
        echo "$usage" >&2
        return 2
    fi

    local binary_path
    if command_exists "whence"; then
        binary_path="$(whence -p "$binary_name")" || binary_path=''
        if [ -n "$binary_path" ]; then
            printf '%s' "$binary_path"
            return 0
        else
            return 1
        fi
    fi

    if command_exists "which"; then
        binary_path="$(which "$binary_name")" || binary_path=''
        if [ -n "$binary_path" ]; then
            printf '%s' "$binary_path"
            return 0
        else
            return 1
        fi
    fi

    if command_exists "type"; then
        binary_path="$(type -P "$binary_name")" || binary_path=''
        if [ -n "$binary_path" ]; then
            printf '%s' "$binary_path"
            return 0
        else
            return 1
        fi
    fi

    echo "find_binary: Could not find a suitable command to find '$binary_name'." >&2
    return 2
}
