#!/usr/bin/env bash


function longest_common_prefix() {
    # set -e

    local -r nl=$'\n'
    local -r usage="
Usage: longest_common_prefix <path> [path…]


Examples:
    longest_common_prefix ./ ./foo.sh ./bar.sh
    longest_common_prefix /dev/proc /dev/proc/1 /dev/proc/2
"

    if [ "$#" -lt 1 ]; then
        echo "Missing required argument.${nl}${usage}" >&2
        return 2
    fi
    if [ "$1" = "--help" ]; then
        echo "$usage"
        return 0
    fi
    if [ "$#" -eq 1 ]; then
        echo "$1"
        return 0
    fi

    local dirname_bin
    dirname_bin="$(find_binary "dirname")"

    # based on code from https://stackoverflow.com/a/12341334

    declare -a names
    declare -a parts
    declare i=0

    names=("$@")
    name="$1"
    while x=$($dirname_bin "$name"); [ "$x" != "/" ]
    do
        parts[$i]="$x"
        i=$(($i + 1))
        name="$x"
    done

    for prefix in "${parts[@]}" /
    do
        for name in "${names[@]}"
        do
            if [ "${name#"$prefix"/}" = "${name}" ]
            then continue 2
            fi
        done
        echo "$prefix"
        break
    done
}
