#!/usr/bin/env bash


# Concatenates $1 to the beginning of $PATH, removing it from elsewhere in $PATH if it exists already.
function path_prepend() {
    # set -e

    path_remove "$1"
    PATH="$1${PATH:+":$PATH"}"
    export PATH
}
