#!/usr/bin/env bash


# Removes matches of $1 from $PATH.
function path_removematch() {
    # set -e

    local -r pattern="$1"

    local sed_bin
    sed_bin="$(find_binary "sed")"
    local grep_bin
    grep_bin="$(find_binary "grep")"

    p="$(path_sep)"
    PATH=$(printf '%s' "$PATH" | $sed_bin 's/'"$p"'/\n/g' | $grep_bin -v "$pattern" | $sed_bin ':a; N; $!ba; s/\n/'"$p"'/g')
    export PATH
}
