#!/usr/bin/env sh


# ⚠️ Part of core "phook" functionality.
#   - Be careful of circular dependencies.
#   - Be careful of POSIX sh compatibility.

phook_enqueue_funcname() {
    if [ -z "$1" ]; then
        return 2
    fi
    _phook_enqueue "${phook_directive_escape_seq:?}&$1"
}
