#!/usr/bin/env sh


shell_actual() {
    if ! (ps -p $$ -o comm=) 2> /dev/null ; then
        #ps command failed, try Busybox ps.
        ps -o ppid,pid,comm | awk "index(\"$$\", \$2) {print \$NF}"
    fi
}
