#!/usr/bin/env bash


function test_session_interactivity() {
    # set -e

    if [ -n "$BASH_VERSION" ]; then
        if [[ $- == *i* ]]; then
            return 0
        else
            return 1
        fi
    elif [ -n "$ZSH_VERSION" ]; then
        if [[ -o interactive ]]; then
            return 0
        else
            return 1
        fi
    else
        echo "Unknown shell: '$SHELL'." >&2
        return 2
    fi
}
